services:
    _defaults:
        autowire: true
        autoconfigure: true

    HeimrichHannot\FlareBundle\EventListener\Integration\Terminal42ChangelanguageListener:
        calls:
            - setMultilingualQueryBuilderFactory: [ '@?Terminal42\DcMultilingualBundle\QueryBuilder\MultilingualQueryBuilderFactoryInterface' ]
